# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tasarim.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1072, 571)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1061, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(320, 90, 331, 321))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.k_adi = QtWidgets.QLineEdit(self.groupBox)
        self.k_adi.setGeometry(QtCore.QRect(140, 80, 113, 20))
        self.k_adi.setObjectName("k_adi")
        self.sf = QtWidgets.QLineEdit(self.groupBox)
        self.sf.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.sf.setObjectName("sf")
        self.giris = QtWidgets.QPushButton(self.groupBox)
        self.giris.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.giris.setObjectName("giris")
        self.mesaj = QtWidgets.QLabel(self.groupBox)
        self.mesaj.setGeometry(QtCore.QRect(15, 290, 301, 20))
        self.mesaj.setText("")
        self.mesaj.setObjectName("mesaj")
        self.a = QtWidgets.QLabel(self.groupBox)
        self.a.setGeometry(QtCore.QRect(55, 80, 61, 20))
        self.a.setObjectName("a")
        self.b = QtWidgets.QLabel(self.groupBox)
        self.b.setGeometry(QtCore.QRect(70, 120, 46, 13))
        self.b.setObjectName("b")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.c = QtWidgets.QLabel(self.tab_2)
        self.c.setGeometry(QtCore.QRect(140, 240, 46, 13))
        self.c.setObjectName("c")
        self.d = QtWidgets.QLabel(self.tab_2)
        self.d.setGeometry(QtCore.QRect(130, 270, 61, 20))
        self.d.setObjectName("d")
        self.ekle = QtWidgets.QPushButton(self.tab_2)
        self.ekle.setGeometry(QtCore.QRect(210, 400, 75, 23))
        self.ekle.setObjectName("ekle")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 310, 111, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.e = QtWidgets.QLabel(self.tab_2)
        self.e.setGeometry(QtCore.QRect(140, 320, 46, 13))
        self.e.setObjectName("e")
        self.tc = QtWidgets.QLineEdit(self.tab_2)
        self.tc.setGeometry(QtCore.QRect(220, 240, 113, 20))
        self.tc.setObjectName("tc")
        self.ad_soyad = QtWidgets.QLineEdit(self.tab_2)
        self.ad_soyad.setGeometry(QtCore.QRect(220, 270, 113, 20))
        self.ad_soyad.setObjectName("ad_soyad")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(440, 20, 511, 391))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.FotografCek = QtWidgets.QPushButton(self.tab_2)
        self.FotografCek.setGeometry(QtCore.QRect(620, 460, 75, 23))
        self.FotografCek.setObjectName("FotografCek")
        self.KameraAc = QtWidgets.QPushButton(self.tab_2)
        self.KameraAc.setGeometry(QtCore.QRect(820, 470, 75, 23))
        self.KameraAc.setObjectName("KameraAc")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 311, 231))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(60, 330, 171, 191))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.FotografCek_2 = QtWidgets.QPushButton(self.tab_3)
        self.FotografCek_2.setGeometry(QtCore.QRect(30, 260, 75, 23))
        self.FotografCek_2.setObjectName("FotografCek_2")
        self.KameraAc_2 = QtWidgets.QPushButton(self.tab_3)
        self.KameraAc_2.setGeometry(QtCore.QRect(140, 260, 75, 23))
        self.KameraAc_2.setObjectName("KameraAc_2")
        self.ogr_list = QtWidgets.QTableWidget(self.tab_3)
        self.ogr_list.setGeometry(QtCore.QRect(440, 40, 191, 171))
        self.ogr_list.setObjectName("ogr_list")
        self.ogr_list.setColumnCount(0)
        self.ogr_list.setRowCount(0)
        self.ogr_list2 = QtWidgets.QTableWidget(self.tab_3)
        self.ogr_list2.setGeometry(QtCore.QRect(320, 310, 361, 192))
        self.ogr_list2.setObjectName("ogr_list2")
        self.ogr_list2.setColumnCount(0)
        self.ogr_list2.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(520, 10, 101, 22))
        self.comboBox.setObjectName("comboBox")
        self.x = QtWidgets.QLabel(self.tab_3)
        self.x.setGeometry(QtCore.QRect(440, 10, 61, 16))
        self.x.setObjectName("x")
        self.mse_button = QtWidgets.QPushButton(self.tab_3)
        self.mse_button.setGeometry(QtCore.QRect(360, 270, 75, 23))
        self.mse_button.setObjectName("mse_button")
        self.psnr_button = QtWidgets.QPushButton(self.tab_3)
        self.psnr_button.setGeometry(QtCore.QRect(460, 270, 75, 23))
        self.psnr_button.setObjectName("psnr_button")
        self.ssim_button = QtWidgets.QPushButton(self.tab_3)
        self.ssim_button.setGeometry(QtCore.QRect(570, 270, 75, 23))
        self.ssim_button.setObjectName("ssim_button")
        self.slider = QtWidgets.QSlider(self.tab_3)
        self.slider.setGeometry(QtCore.QRect(370, 220, 160, 22))
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName("slider")
        self.g_ekle = QtWidgets.QPushButton(self.tab_3)
        self.g_ekle.setGeometry(QtCore.QRect(600, 220, 75, 23))
        self.g_ekle.setObjectName("g_ekle")
        self.deger = QtWidgets.QLineEdit(self.tab_3)
        self.deger.setGeometry(QtCore.QRect(540, 220, 51, 20))
        self.deger.setReadOnly(True)
        self.deger.setObjectName("deger")
        self.m_deger = QtWidgets.QLineEdit(self.tab_3)
        self.m_deger.setGeometry(QtCore.QRect(370, 290, 51, 20))
        self.m_deger.setReadOnly(True)
        self.m_deger.setObjectName("m_deger")
        self.p_deger = QtWidgets.QLineEdit(self.tab_3)
        self.p_deger.setGeometry(QtCore.QRect(470, 290, 51, 20))
        self.p_deger.setReadOnly(True)
        self.p_deger.setObjectName("p_deger")
        self.s_deger = QtWidgets.QLineEdit(self.tab_3)
        self.s_deger.setGeometry(QtCore.QRect(580, 290, 51, 20))
        self.s_deger.setReadOnly(True)
        self.s_deger.setObjectName("s_deger")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(710, 20, 171, 201))
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.sonuc = QtWidgets.QLabel(self.tab_3)
        self.sonuc.setGeometry(QtCore.QRect(710, 260, 171, 201))
        self.sonuc.setText("")
        self.sonuc.setObjectName("sonuc")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(710, 220, 171, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(720, 490, 151, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(30, 300, 81, 21))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 300, 141, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(920, 290, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(920, 320, 46, 13))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(930, 420, 111, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(930, 440, 46, 13))
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.giris.setText(_translate("Dialog", "Giriş Yap"))
        self.a.setText(_translate("Dialog", "Kullanıcı Adı:"))
        self.b.setText(_translate("Dialog", "Şifre:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Giriş Yap"))
        self.c.setText(_translate("Dialog", "Tc.No:"))
        self.d.setText(_translate("Dialog", "Adı Soyadı:"))
        self.ekle.setText(_translate("Dialog", "Ekle"))
        self.e.setText(_translate("Dialog", "Sınıf:"))
        self.FotografCek.setText(_translate("Dialog", "Fotoğraf Çek"))
        self.KameraAc.setText(_translate("Dialog", "Kamera Aç"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Öğrenci Ekle"))
        self.FotografCek_2.setText(_translate("Dialog", "Fotoğraf Çek"))
        self.KameraAc_2.setText(_translate("Dialog", "Kamera Aç"))
        self.x.setText(_translate("Dialog", "Sınıf Seçiniz:"))
        self.mse_button.setText(_translate("Dialog", "MSE"))
        self.psnr_button.setText(_translate("Dialog", "PSNR"))
        self.ssim_button.setText(_translate("Dialog", "SSİM"))
        self.g_ekle.setText(_translate("Dialog", "Gürültü Ekle"))
        self.label_4.setText(_translate("Dialog", "Bulunan Yüzler:"))
        self.label_5.setText(_translate("Dialog", "Geldiği Gün Sayısı:"))
        self.label_7.setText(_translate("Dialog", "Gelmediği Gün Sayısı:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Benzerlik ve Devamsızlık Kontrolü"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

